version: '3.7'

networks:
  internal:
    ipam:
      config:
        - subnet: 172.20.53.0/24
    driver_opts:
      com.docker.network.driver.mtu: 4096

services:
  auth:
    build:
      context: pdns
      dockerfile: Dockerfile-auth
    image: desec/pqdnssec-auth:latest
    user: root
    volumes:
      - ./auth.conf:/etc/powerdns/pdns.d/auth.conf
    environment:
      - PDNS_AUTH_API_KEY='insecure'
    ports:
      - "${PUBLIC_TCP_UDP_PORT_AUTH:-5301}:53/tcp"
      - "${PUBLIC_TCP_UDP_PORT_AUTH:-5301}:53/udp"
      - "127.0.0.1:5391:8081/tcp"
    networks:
      internal:
        ipv4_address: 172.20.53.101

  recursor:
    build:
      context: pdns
      dockerfile: Dockerfile-recursor
    image: desec/pqdnssec-resolver:latest
    user: root
    volumes:
      - ./recursor.conf:/etc/powerdns/recursor.d/recursor.conf
      - ./recursor.lua:/etc/powerdns/recursor.lua
    environment:
      - PDNS_RECURSOR_API_KEY='insecure'
      - DESEC_DOMAIN
    ports:
      - "${PUBLIC_TCP_UDP_PORT_RECURSOR:-5302}:53/tcp"
      - "${PUBLIC_TCP_UDP_PORT_RECURSOR:-5302}:53/udp"
      - "127.0.0.1:5392:8082/tcp"
    networks:
      internal:
        ipv4_address: 172.20.53.102

  dnsdist:
    build:
      context: pdns
      dockerfile: Dockerfile-dnsdist
    image: desec/pqdnssec-dnsdist:latest
    volumes:
      - ./dnsdist.conf:/etc/dnsdist/dnsdist.conf
    ports:
      - "127.0.0.1:5383:80/tcp"
    networks:
      internal:
        ipv4_address: 172.20.53.103

  www:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./web/dist:/webapp
    environment:
      - DESEC_DOMAIN
      - DESEC_DOMAIN_REDIRECT
    networks:
      internal:
        ipv4_address: 172.20.53.200


volumes:
  caddy_data:
  caddy_config:
